#server.port=8080
#server.address=0.0.0.0
#
#spring.application.name=history-ar-backend
#
#spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.gfualrlzqenuressyeli
#spring.datasource.password=Illupy1@3$5
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.servlet.multipart.max-file-size=150MB
#spring.servlet.multipart.max-request-size=150MB
#
#file.upload-dir=${user.dir}/uploads
#
## -----------------------------------------------
## Storage provider: "local" | "supabase"
## -----------------------------------------------
#storage.type=supabase
#
## Supabase Storage (active when storage.type=supabase)
## URL: https://<project-ref>.supabase.co
#supabase.url=https://gfualrlzqenuressyeli.supabase.co
## Service-role key: Supabase Dashboard > Settings > API > service_role
#supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmdWFscmx6cWVudXJlc3N5ZWxpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzg2MjAyNSwiZXhwIjoyMDg5NDM4MDI1fQ.ctvRbGXUWNBvPMhopLw5-7QkYbMiP97QmfbxZ6v8dV0
## Bucket name (auto-created as public on first startup)
#supabase.storage.bucket=ar-history-assets
#
## JWT
#jwt.secret=ArHistorySecretKey2026VeryLongSecretKeyForHS256Algorithm!@#$%
#jwt.expiration=86400000
#
## Mail (Gmail SMTP)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=tailuuduc2004@gmail.com
#spring.mail.password=akmc azzm pmnh abaj
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## Frontend URL for reset password link
#app.frontend-url=http://103.178.235.163
##




server.port=${PORT:8080}
#server.address=0.0.0.0

spring.application.name=history-ar-backend

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB

file.upload-dir=${user.dir}/uploads

# -----------------------------------------------
# Storage provider: "local" | "supabase"
# -----------------------------------------------
storage.type=supabase

# Supabase Storage (active when storage.type=supabase)
# URL: https://<project-ref>.supabase.co
supabase.url=${SUPABASE_URL}
# Service-role key: Supabase Dashboard > Settings > API > service_role
supabase.service-key=${SUPABASE_SERVICE_KEY}
# Bucket name (auto-created as public on first startup)
supabase.storage.bucket=ar-history-assets

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL for reset password link
app.frontend-url=http://103.178.235.163